# Generated by Django 4.2.7 on 2023-12-08 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('propertyid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('features', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properity_userid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('unitid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('rent_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_type', models.CharField(choices=[('1BHK', '1BHK'), ('2BHK', '2BHK'), ('1BHK', '3BHK'), ('4BHK', '4BHK')], max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units_userid', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='RealEstate.property')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('tenantid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('documents', models.FileField(blank=True, null=True, upload_to='tenant/document')),
                ('agreement_end_date', models.DateField()),
                ('monthly_rent_date', models.DateField()),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='RealEstate.units')),
            ],
        ),
    ]
