# Generated by Django 4.2.7 on 2023-12-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstate', '0002_property_units_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
